import RecognitionScience.Constants
import RecognitionScience.Cost
import RecognitionScience.Foundation.QuarkColors

/-!
# Paper: Quark Confinement and the Matter-Sector Mass-Gap Floor on the Recognition Lattice

Self-contained Lean 4 proof companion for the paper
"Quark Confinement and the Matter-Sector Mass-Gap Floor from Recognition
Science: A Machine-Verified Discrete-Lattice Derivation"
(Washburn, April 2026).

This module is intentionally self-contained: it depends only on
`RecognitionScience.Constants`, `RecognitionScience.Cost`, and
`RecognitionScience.Foundation.QuarkColors`, all of which are already
in the public Recognition Science framework that includes the
T0--T8 forcing chain.

## Two coupled theorems

1. **Confinement from ledger topology** (Section 5 of the paper).
   The J-cost of separating a non-singlet color excitation by `r`
   φ-rungs on the recognition lattice is `J(φ^r)`, which is zero at
   `r = 0`, strictly positive at every `r ≥ 1`, strictly monotone in
   `r`, and divergent as `r → ∞`. The color singlet is the unique
   strict cost minimizer; isolated quarks are not in the spectrum.

2. **Matter-sector mass-gap floor** (Section 6 of the paper).
   The first-rung holonomy phase of the recognition connection
   equals `J(φ) = φ - 3/2`. The matter-sector mass-squared floor
   above the canonical vacuum is `m_gap² = J(φ) · ℏ_R`, which sits
   below both `M_W²` and `M_Z²` in canonical units.

## Master certificates

The paper packages two certificates: `QCDConfinementFromLedgerCert`
(eight clauses) and `YangMillsMassGapCert` (eight clauses). Both
are inhabited (`qcdConfinementFromLedgerCert` and
`yangMillsMassGapCert`).

## Status

Zero `sorry`, zero RS-internal axioms. Compiles against the public
framework's lean-toolchain (currently `leanprover/lean4:v4.27.0-rc1`).

The companion paper text and PDF are maintained separately. The Lean
proofs here are the formal substrate; the paper carries the prose
derivation in full.

## Build instructions

```bash
lake exe cache get          -- one-time Mathlib cache (~2 GB)
lake build RecognitionScience.Papers.YangMillsMassGap
```

The transitive dependency closure for this module is small: only
`Constants`, `Cost`, and `Foundation.QuarkColors` (with
`PhiForcing`, `PhiForcingDerived`, `DimensionForcing`,
`ParticleGenerations`, `LawOfExistence`, `DiscretenessForcing`
pulled in transitively). A clean cold build takes about a minute
on top of the Mathlib cache.

## Paper-to-module map

| Paper section | Lean theorem (in this module) |
|---|---|
| Section 5: cost-floor singlet ($J(\varphi^0) = 0$) | `separation_cost_zero_at_singlet` |
| Section 5: positivity off the singlet | `separation_cost_pos` |
| Section 5: strict monotonicity | `separation_cost_strict_mono` |
| Section 5: unboundedness | `separation_cost_unbounded` |
| Section 5: singlet uniquely minimizes | `singlet_uniquely_minimizes` |
| Section 5: no isolated quark | `no_isolated_quark` |
| Section 5: master cert | `qcdConfinementFromLedgerCert` |
| Section 6: first-rung holonomy phase | `holonomy_phase_first_rung` |
| Section 6: $J(\varphi) > 0$ | `jPhi_pos` |
| Section 6: $J(\varphi) \in (0.11, 0.13)$ | `jPhi_band` |
| Section 6: gap squared positive | `mass_gap_squared_pos` |
| Section 6: gap squared band | `mass_gap_squared_band` |
| Section 6: gap saturates first rung | `mass_gap_squared_eq_first_rung_phase` |
| Section 6: gap below $M_W^2$ | `mass_gap_below_W_mass_squared` |
| Section 6: gap below $M_Z^2$ | `mass_gap_below_Z_mass_squared` |
| Section 6: master cert | `yangMillsMassGapCert` |
-/

namespace RecognitionScience
namespace Papers
namespace YangMillsMassGap

open Constants
open RecognitionScience.Cost

noncomputable section

/-! ## §1. The separation cost on the φ-ladder

We model an isolated color non-singlet as a single-color face-pair
excitation on the Q₃ lattice with its compensating face-pair held at
separation rung `r` on the φ-ladder generated by the recognition
self-similarity (T6). The J-cost of maintaining the separation is
`J(φ^r)`. -/

/-- The separation cost: J(φ^r). -/
def separation_cost (r : ℕ) : ℝ := Jcost (phi ^ r)

/-- The singlet (rung 0) sits exactly at the J-cost minimum. -/
theorem separation_cost_zero_at_singlet :
    separation_cost 0 = 0 := by
  unfold separation_cost
  rw [pow_zero]
  exact Jcost_unit0

/-! ## §2. Strict positivity off the singlet -/

/-- Auxiliary: `phi^r > 1` for every `r ≥ 1`. -/
private theorem phi_pow_gt_one (r : ℕ) (hr : 0 < r) : 1 < phi ^ r := by
  have h_phi : 1 < phi := one_lt_phi
  calc (1 : ℝ) = phi ^ 0 := by rw [pow_zero]
    _ < phi ^ r := pow_lt_pow_right₀ h_phi hr

/-- Auxiliary: `phi^r ≠ 1` for every `r ≥ 1`. -/
private theorem phi_pow_ne_one (r : ℕ) (hr : 0 < r) : phi ^ r ≠ 1 :=
  ne_of_gt (phi_pow_gt_one r hr)

/-- **THEOREM (no isolated quark is degenerate with the singlet).**
For every rung `r ≥ 1`, the separation cost is strictly positive. -/
theorem separation_cost_pos (r : ℕ) (hr : 0 < r) : 0 < separation_cost r := by
  unfold separation_cost
  have hphi_pos : 0 < phi := phi_pos
  have hpk : 0 < phi ^ r := pow_pos hphi_pos r
  exact Jcost_pos_of_ne_one (phi ^ r) hpk (phi_pow_ne_one r hr)

/-! ## §3. Strict monotonicity in the separation rung -/

/-- Auxiliary: `Jcost` is strictly monotone on `[1, ∞)`. We only
need the integer-rung specialisation on the φ-ladder. -/
private theorem jcost_strict_mono_ge_one
    {x y : ℝ} (hx : 1 ≤ x) (hxy : x < y) : Jcost x < Jcost y := by
  have hx_pos : (0 : ℝ) < x := by linarith
  have hy_pos : (0 : ℝ) < y := by linarith
  have hx_ne : x ≠ 0 := ne_of_gt hx_pos
  have hy_ne : y ≠ 0 := ne_of_gt hy_pos
  rw [Jcost_eq_sq hx_ne, Jcost_eq_sq hy_ne]
  have h_2x_pos : (0 : ℝ) < 2 * x := by linarith
  have h_2y_pos : (0 : ℝ) < 2 * y := by linarith
  rw [div_lt_div_iff₀ h_2x_pos h_2y_pos]
  have h_expand : (y - 1) ^ 2 * (2 * x) - (x - 1) ^ 2 * (2 * y)
      = 2 * (y - x) * (x * y - 1) := by ring
  have h_yx : 0 < y - x := by linarith
  have h_xy_gt_one : 1 < x * y := by
    have h_one_le_x : (1 : ℝ) ≤ x := hx
    have h_one_lt_y : (1 : ℝ) < y := lt_of_le_of_lt hx hxy
    nlinarith
  have h_pos : 0 < 2 * (y - x) * (x * y - 1) := by
    have h1 : 0 < 2 * (y - x) := by linarith
    have h2 : 0 < x * y - 1 := by linarith
    exact mul_pos h1 h2
  linarith [h_pos, h_expand]

/-- **THEOREM (separation cost strictly monotone).**  Pulling the
antiquark one rung farther always strictly increases the J-cost. -/
theorem separation_cost_strict_mono (r s : ℕ) (hrs : r < s) :
    separation_cost r < separation_cost s := by
  unfold separation_cost
  have h_phi : 1 < phi := one_lt_phi
  have h_phi_le : (1 : ℝ) ≤ phi ^ r := by
    rcases Nat.eq_zero_or_pos r with hr0 | hr_pos
    · rw [hr0, pow_zero]
    · exact le_of_lt (phi_pow_gt_one r hr_pos)
  have h_pow_lt : phi ^ r < phi ^ s :=
    pow_lt_pow_right₀ h_phi hrs
  exact jcost_strict_mono_ge_one h_phi_le h_pow_lt

/-! ## §4. Unbounded growth of the separation cost -/

/-- Auxiliary: `phi^r → ∞` as `r → ∞`. -/
private theorem phi_pow_tendsto_atTop :
    Filter.Tendsto (fun r : ℕ => (phi : ℝ) ^ r) Filter.atTop Filter.atTop :=
  tendsto_pow_atTop_atTop_of_one_lt one_lt_phi

/-- **THEOREM (separation cost unbounded).**  As `r → ∞`, the J-cost
of maintaining a non-singlet at separation rung `r` tends to `+∞`.

Proof: `J(x) = (x + x⁻¹)/2 - 1 ≥ x/2 - 1` for `x > 0` (since `x⁻¹ ≥ 0`).
For `x = phi^r → ∞`, this lower bound diverges. -/
theorem separation_cost_unbounded :
    Filter.Tendsto separation_cost Filter.atTop Filter.atTop := by
  apply Filter.tendsto_atTop_mono (f := fun r : ℕ => (phi : ℝ) ^ r / 2 - 1)
  · intro r
    unfold separation_cost
    have hphi_pos : (0 : ℝ) < phi := phi_pos
    have hpk : (0 : ℝ) < phi ^ r := pow_pos hphi_pos r
    have h_inv_nonneg : (0 : ℝ) ≤ (phi ^ r)⁻¹ := le_of_lt (inv_pos.mpr hpk)
    unfold Jcost
    linarith
  · have h_pow := phi_pow_tendsto_atTop
    have h_div : Filter.Tendsto (fun r : ℕ => (phi : ℝ) ^ r / 2)
        Filter.atTop Filter.atTop := by
      apply Filter.Tendsto.atTop_div_const (by norm_num : (0 : ℝ) < 2)
      exact h_pow
    rw [Filter.tendsto_atTop_atTop] at h_div ⊢
    intro M
    obtain ⟨N, hN⟩ := h_div (M + 1)
    refine ⟨N, fun n hn => ?_⟩
    have := hN n hn
    linarith

/-! ## §5. Singlet uniqueness and the no-isolated-quark theorem -/

/-- **THEOREM (singlet uniquely minimizes).**  For every `r ≥ 1`,
`separation_cost 0 < separation_cost r`. -/
theorem singlet_uniquely_minimizes (r : ℕ) (hr : 0 < r) :
    separation_cost 0 < separation_cost r := by
  rw [separation_cost_zero_at_singlet]
  exact separation_cost_pos r hr

/-- **NO-ISOLATED-QUARK THEOREM.**  There is no integer rung `r ≥ 1`
at which an isolated quark state has the same J-cost as the color
singlet. Equivalently, every non-singlet state strictly exceeds the
singlet floor. -/
theorem no_isolated_quark :
    ∀ r : ℕ, 0 < r → separation_cost 0 < separation_cost r :=
  singlet_uniquely_minimizes

/-! ## §6. Master certificate for the confinement half -/

/-- **QCD CONFINEMENT FROM LEDGER TOPOLOGY MASTER CERTIFICATE.**

Eight clauses, all derived from J-cost positivity + φ-ladder
self-similarity + `N_colors D_physical = 3`.
-/
structure QCDConfinementFromLedgerCert where
  singlet_zero : separation_cost 0 = 0
  non_singlet_pos : ∀ r : ℕ, 0 < r → 0 < separation_cost r
  mono : ∀ r s : ℕ, r < s → separation_cost r < separation_cost s
  unbounded : Filter.Tendsto separation_cost Filter.atTop Filter.atTop
  singlet_minimizes : ∀ r : ℕ, 0 < r → separation_cost 0 < separation_cost r
  no_free_quark : ∀ r : ℕ, 0 < r → separation_cost 0 < separation_cost r
  three_colors : Foundation.QuarkColors.N_colors
                   Foundation.DimensionForcing.D_physical = 3
  first_rung_band : 0.11 < separation_cost 1 ∧ separation_cost 1 < 0.13

/-- The first-rung separation cost equals the canonical golden-section
J-cost band `J(φ) ∈ (0.11, 0.13)`. -/
theorem first_rung_band : 0.11 < separation_cost 1 ∧ separation_cost 1 < 0.13 := by
  unfold separation_cost
  rw [pow_one]
  have hphi_pos : 0 < phi := phi_pos
  have hne : phi ≠ 0 := ne_of_gt hphi_pos
  -- J(φ) = φ - 3/2
  have h_phisq : phi * phi = phi + 1 := by
    have h := phi_sq_eq
    nlinarith [sq phi]
  have h_inv : phi⁻¹ = phi - 1 := by
    have hprod : phi * (phi - 1) = 1 := by nlinarith [h_phisq]
    field_simp at hprod ⊢
    linarith
  have h_jphi : Jcost phi = phi - 3 / 2 := by
    unfold Jcost
    rw [h_inv]
    ring
  rw [h_jphi]
  refine ⟨?_, ?_⟩
  · have h_lo : (1.61 : ℝ) < phi := phi_gt_onePointSixOne
    linarith
  · have h_hi : phi < (1.62 : ℝ) := phi_lt_onePointSixTwo
    linarith

/-- The master certificate is inhabited. -/
def qcdConfinementFromLedgerCert : QCDConfinementFromLedgerCert where
  singlet_zero := separation_cost_zero_at_singlet
  non_singlet_pos := separation_cost_pos
  mono := separation_cost_strict_mono
  unbounded := separation_cost_unbounded
  singlet_minimizes := singlet_uniquely_minimizes
  no_free_quark := no_isolated_quark
  three_colors := Foundation.QuarkColors.three_colors_forced
  first_rung_band := first_rung_band

/-! ## §7. The matter sector and the holonomy phase

The matter sector of the recognition Hilbert space carries a
canonical action quantum `ℏ_R`, normalised to 1 in RS-native units
(`ℏ_R = E_coh · τ₀ = φ⁻⁵ · 1`, but rescaled so that the canonical
sector eigenvalue `λ_Z = 1`).

The recognition connection on the φ-ladder has holonomy
`θ_hol(k) := Jcost (phi^k)` around the k-th rung loop. -/

/-- The first-rung J-cost. -/
def jPhi : ℝ := Jcost phi

/-- Closed form: `J(φ) = φ - 3/2`. -/
theorem jPhi_eq : jPhi = phi - 3 / 2 := by
  unfold jPhi
  have hphi_pos : 0 < phi := phi_pos
  have hne : phi ≠ 0 := ne_of_gt hphi_pos
  have h_phisq : phi * phi = phi + 1 := by
    have h := phi_sq_eq
    nlinarith [sq phi]
  have h_inv : phi⁻¹ = phi - 1 := by
    have hprod : phi * (phi - 1) = 1 := by nlinarith [h_phisq]
    field_simp at hprod ⊢
    linarith
  unfold Jcost
  rw [h_inv]
  ring

/-- `J(φ) > 0`. -/
theorem jPhi_pos : 0 < jPhi := by
  unfold jPhi
  exact Jcost_pos_of_ne_one phi phi_pos (ne_of_gt one_lt_phi)

/-- `J(φ) ∈ (0.11, 0.13)`. -/
theorem jPhi_band : 0.11 < jPhi ∧ jPhi < 0.13 := by
  rw [jPhi_eq]
  refine ⟨?_, ?_⟩
  · have h_lo : (1.61 : ℝ) < phi := phi_gt_onePointSixOne
    linarith
  · have h_hi : phi < (1.62 : ℝ) := phi_lt_onePointSixTwo
    linarith

/-- The recognition holonomy phase at rung `k`. -/
def holonomy_phase (k : ℕ) : ℝ := Jcost (phi ^ k)

/-- First-rung holonomy phase: `θ_hol(1) = J(φ)`. -/
theorem holonomy_phase_first_rung :
    holonomy_phase 1 = jPhi := by
  unfold holonomy_phase jPhi
  rw [pow_one]

/-- The matter-sector action quantum `ℏ_R` in RS-native units.
Normalised so `λ_Z · ℏ_R = M_Z²` with `λ_Z = 1`. -/
def hbar_R : ℝ := 1

theorem hbar_R_pos : 0 < hbar_R := by unfold hbar_R; norm_num

/-! ## §8. The mass-gap floor -/

/-- The matter-sector mass-squared gap, RS-native: `m_gap² = J(φ) · ℏ_R`. -/
def mass_gap_squared : ℝ := jPhi * hbar_R

theorem mass_gap_squared_pos : 0 < mass_gap_squared :=
  mul_pos jPhi_pos hbar_R_pos

theorem mass_gap_squared_band :
    0.11 < mass_gap_squared ∧ mass_gap_squared < 0.13 := by
  unfold mass_gap_squared hbar_R
  obtain ⟨h_lo, h_hi⟩ := jPhi_band
  refine ⟨?_, ?_⟩
  · linarith
  · linarith

/-- The gap saturates the first-rung holonomy phase. -/
theorem mass_gap_squared_eq_first_rung_phase :
    mass_gap_squared = holonomy_phase 1 * hbar_R := by
  unfold mass_gap_squared
  rw [holonomy_phase_first_rung]

/-- The W mass squared in RS-native units: `M_W² = (3 + φ)/6 = cos²θ_W`. -/
def M_W_squared : ℝ := ((3 + phi) / 6) * hbar_R

/-- The Z mass squared in RS-native units: `M_Z² = ℏ_R = 1`. -/
def M_Z_squared : ℝ := 1 * hbar_R

theorem M_W_squared_pos : 0 < M_W_squared := by
  unfold M_W_squared
  have h1 : 0 < (3 + phi) / 6 := by
    have hphi : (0 : ℝ) < phi := phi_pos
    have hnum : (0 : ℝ) < 3 + phi := by linarith
    exact div_pos hnum (by norm_num)
  exact mul_pos h1 hbar_R_pos

theorem M_Z_squared_pos : 0 < M_Z_squared := by
  unfold M_Z_squared
  rw [one_mul]; exact hbar_R_pos

/-- **THEOREM (mass-gap floor below W mass squared).** -/
theorem mass_gap_below_W_mass_squared :
    mass_gap_squared < M_W_squared := by
  unfold mass_gap_squared M_W_squared hbar_R
  obtain ⟨_, h_hi⟩ := jPhi_band
  have h_lo : (1.61 : ℝ) < phi := phi_gt_onePointSixOne
  have h_W : (0.768 : ℝ) < (3 + phi) / 6 := by
    have h1 : (3 + phi) > 4.61 := by linarith
    have h2 : (3 + phi) / 6 > 4.61 / 6 :=
      div_lt_div_of_pos_right h1 (by norm_num : (0 : ℝ) < 6)
    linarith
  nlinarith

/-- **THEOREM (mass-gap floor below Z mass squared).** -/
theorem mass_gap_below_Z_mass_squared :
    mass_gap_squared < M_Z_squared := by
  unfold M_Z_squared
  rw [one_mul]
  obtain ⟨_, h_hi⟩ := mass_gap_squared_band
  unfold hbar_R
  linarith

/-! ## §9. Master certificate for the mass-gap half -/

/-- **YANG-MILLS MASS GAP MASTER CERTIFICATE.**  Eight clauses. -/
structure YangMillsMassGapCert where
  jPhi_pos_cert : 0 < jPhi
  jPhi_band_cert : 0.11 < jPhi ∧ jPhi < 0.13
  mass_gap_pos_cert : 0 < mass_gap_squared
  mass_gap_band_cert : 0.11 < mass_gap_squared ∧ mass_gap_squared < 0.13
  gap_eq_first_rung : mass_gap_squared = holonomy_phase 1 * hbar_R
  gap_below_W : mass_gap_squared < M_W_squared
  gap_below_Z : mass_gap_squared < M_Z_squared
  three_colors : Foundation.QuarkColors.N_colors
                   Foundation.DimensionForcing.D_physical = 3

def yangMillsMassGapCert : YangMillsMassGapCert where
  jPhi_pos_cert := jPhi_pos
  jPhi_band_cert := jPhi_band
  mass_gap_pos_cert := mass_gap_squared_pos
  mass_gap_band_cert := mass_gap_squared_band
  gap_eq_first_rung := mass_gap_squared_eq_first_rung_phase
  gap_below_W := mass_gap_below_W_mass_squared
  gap_below_Z := mass_gap_below_Z_mass_squared
  three_colors := Foundation.QuarkColors.three_colors_forced

/-! ## §10. One-statement summary -/

/-- **PAPER ONE-STATEMENT THEOREM.**

The discrete-lattice Yang-Mills mass gap on the recognition lattice:
1. The color singlet ($r=0$) sits at the J-cost minimum;
2. Every non-singlet rung carries strictly positive cost;
3. The cost is strictly monotone in the separation rung;
4. The cost diverges as the separation grows;
5. The matter-sector mass-squared gap equals `J(φ) · ℏ_R` in
   RS-native units, with `J(φ) ∈ (0.11, 0.13)`;
6. The gap sits below both `M_W²` and `M_Z²`. -/
theorem yang_mills_one_statement :
    separation_cost 0 = 0 ∧
    (∀ r : ℕ, 0 < r → 0 < separation_cost r) ∧
    (∀ r s : ℕ, r < s → separation_cost r < separation_cost s) ∧
    Filter.Tendsto separation_cost Filter.atTop Filter.atTop ∧
    mass_gap_squared = jPhi * hbar_R ∧
    (0.11 < mass_gap_squared ∧ mass_gap_squared < 0.13) ∧
    mass_gap_squared < M_W_squared ∧
    mass_gap_squared < M_Z_squared :=
  ⟨separation_cost_zero_at_singlet,
   separation_cost_pos,
   separation_cost_strict_mono,
   separation_cost_unbounded,
   rfl,
   mass_gap_squared_band,
   mass_gap_below_W_mass_squared,
   mass_gap_below_Z_mass_squared⟩

end

end YangMillsMassGap
end Papers
end RecognitionScience
